# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm test
    - name: Trigger deployment
      # uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
      # with:
      #   serviceId: ${{ secrets.RENDER_SERVICE_ID }}
      #   apiKey: ${{ secrets.RENDER_API_KEY }}
      #   multipleDeployment: false #optional, default true
      env:
          deploy_url: https://api.render.com/deploy/srv-cqchd3uehbks738g7sig?key=9yVFQCDIBJw
      run: |
          curl "$deploy_url"


    
    # - name: Deploy to production
    #   uses: johnbeynon/render-deploy-action@v0.0.8
    #   with:
    #     service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
    #     api-key: ${{ secrets.MY_RENDER_API_KEY }}
    #     wait-for-success: true

